### ISSUE TITLE
Doesn't work in .NET Core 2.2

### ISSUE THREAD

**Issue by ghost** [aberus/ImageVisualizer#7]
![image](https://user-images.githubusercontent.com/16199122/67167635-1b740680-f351-11e9-839a-0d914374a9bf.png)

**Comment by aberus** [comment]
Thank you for reporting an issue.
There was no support for custom visualizers on .NET Core projects (nor UWP projects) in older version of Visual Studio so I did not anticipate to work with .NET Core projects. 

I will try to update the debug visualizer to support .NET Core projects.
 
Which version of Visual Studio are you using (2017 or 2019)?

**Comment by lasharn** [comment]
I have the same issue in Visual Studio 2019

**Comment by aberus** [comment]
Hope it was worth the wait. I made some progress enabling visualizers for .NET Core projects.
I will release 0.7 in coming weeks, but **only .NET Core 3.x projects will be supported**.

There is no proper documentation (and examples) from Microsoft how to convert/write visualizer that support .NET Framework and .NET Core projects. 

@timmackey @lasharn I presume that you were debugging System.Drawing.Bitmap images, because System.Windows.Media namespace is not available in .NET Core 2.2

**Comment by ghost** [comment]
@aberus 
Yes, debugging System.Drawing.Bitmap images.
The visualizer works fine in VS 2017 .NET Framework.
Does not work in VS 2019 Core 3.0.
Consider making the leap to release 1.0
Thanks for giving this your attention.

**Comment by DineshSolanki** [comment]
I'm looking for the same to use it in net core 3.1, Any update?

**Comment by aberus** [comment]
As version 0.7 .NET Core 3.x projects are supported.

.NET Core 2.x project will not be supported, because of limitations in VS and .NET Core 2.x.

**Comment by DineshSolanki** [comment]
Thanks for the update, and I think you should close this issue as won't fix.
